### ISSUE TITLE
More details required in README

### ISSUE THREAD

**Issue by jbradbury** [phnmnl/container-tool-generic_filter#1]
Some more details are required in the description section of the README. Currently there is just a link to the W4M github page, whose README is uninformative.

**Comment by pkrog** [comment]
Hi @jbradbury , I've updated the README. See master branch.

**Comment by jbradbury** [comment]
Thanks @pkrog 

So as these changes are in the master branch, they will be picked up in the new RC?

**Comment by pkrog** [comment]
I can't confirm you that. I didn't work on this aspect. I don't remember who did.
I don't know what is picked up between the master branch or the release tag (v_***_cv_***).
@pcm32 , have you any more information?

**Comment by pcm32** [comment]
Ideally you should never make commits directly to master branch; they generate unnecessary release tagged containers (without the dev_ prefix). At some point one would like to delete dev_* tagged containers, and this will mean that you will have plenty of unneeded images in the long run for this repo.

**Comment by pkrog** [comment]
I think James only wanted to know how the README is extracted from the repos.

**Comment by jbradbury** [comment]
Yes, I am not too sure about the release procedure, @pcm32  is there anything more that needs to be done except merging the develop and master branches? I have made some changes to README files for some containers which I have mostly done by forking and initiating pull requests. 

If I complete the PRs, merging the new READMEs to master, does that count as a new release? Or is there more to it than that?
